#ifndef CONFIG_P4
#define CONFIG_P4

#define FORWARDING_TABLE_CAPACITY       512
#define FLOOD_MULTICAST_GROUP_ID        1

#define ALLREDUCE_MULTICAST_GRPOUP_ID   FLOOD_MULTICAST_GROUP_ID
#define ALLREDUCE_UDP_PORT              4242
#define ALLREDUCE_NUM_WORKERS           2
#define ALLREDUCE_VALUE_BYTES           4
#define ALLREDUCE_EXPONENT_BYTES        4

#define ALLREDUCE_WORKER_TABLE_CAPACITY 32

#endif